### ISSUE TITLE
Crawler is missing activity

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/gharchive.org#171]
It appears that the rate of "missed records" has gone up significantly over the period of the last 12ish months. Looking at the logs from 2014~2015, it was happening a few times a month, and more recently the rate is **significantly** higher. 

Last ~30 days: 
https://gist.github.com/igrigorik/2f39467d7370b88337702506e83b2892

We don't know how much we actually missed, only the fact that we likely did because we fetched a set of results that did not overlap with the previous set. Relevant code:
https://github.com/igrigorik/githubarchive.org/blob/master/crawler/crawler.rb#L89

Current interval is 1.75s. As a temporary patch, I've decreased the query interval from 1.5s to 0.75s. In theory, that should still keep us under the [5000 req/hr limit](https://developer.github.com/v3/#rate-limiting), but that doesn't really resolve the problem long-term. We probably need a higher limit here, plus logic to do pagination whenever we encounter this case  — with the gotcha is that this will introduce some subtle concurrency gotchas that we'll have to guard for in the crawler.

**Comment by lukaszgryglicki** [comment]
@igrigorik @annafil any progress on that?
I've implemented alternate solution by using `ListRepositoryEvents` from GitHub API, but after few days of investigations I'm also wondering...
Is it possible that GitHub API is also missing some events?
See [here](
https://github.com/cncf/devstats/issues/111#issuecomment-405000284)
```
Hi, I'm using ListRepositoryEvents: https://developer.github.com/v3/issues/events/#list-events-for-a-repository to get a list of events for a selected repository.
Is it possible that this function does not return all events?
```

**Comment by igrigorik** [comment]
Yes, it is possible. :)

@annafil has been investigating alternative solutions — fingers crossed.

**Comment by lukaszgryglicki** [comment]
@igrigorik how about implementing a tokens pool? Like for example, you have 3 GitHub tokens and when rate limit error is encountered you just switch to another token? I can work on it if you think that would help and if you are ok with that approach.

**Comment by igrigorik** [comment]
@lukaszgryglicki as it happens, implemented just that last week and after monitoring the logs for past ~4 days, it looks like it's keeping up without missing activity — yay! Unfortunately we won't be able to backfill what we missed, but at least moving forward we should be in good shape.

Closing.

**Comment by lukaszgryglicki** [comment]
Great! Thanks for the info.
