### ISSUE TITLE
Repo name vs URL inconsistent between time periods

### ISSUE THREAD

**Issue by mrwillis** [igrigorik/gharchive.org#176]
Hi!

Thanks for putting this together. I noticed that the `repo.name` and `repo.url` fields are not consistent between end of March 2012 and end of 2014. Specifically, it seems like `repo.name` just gets collapsed to the repo name and not [user]/[reponame] as it is in the URL whereas after 2014 and before 2012, `repo.name` is [user]/[reponame] as it is in the URL. Perhaps this could be backfilled?

Thanks

**Comment by igrigorik** [comment]
Assuming the data is there, backfilling would be a non-trivial exercise. Not impossible, but non-trivial.. 

We ran a large transform/refactor ~1.5 years back (see https://github.com/igrigorik/githubarchive.org/issues/112) and https://github.com/arfon/gh_archive_parser/ — perhaps that could be re-used. That said, first thing to validate would be to check if the necessary data is there for the 2012-2014 period in question.

@mrwillis do you have bandwidth to explore this?
