### ISSUE TITLE
The GitHub Archive project will now be known as “GHArchive” 

### ISSUE THREAD

**Issue by igrigorik** [igrigorik/gharchive.org#178]
### Why is the name changing? 

This project has always been an **unofficial** archive of the GitHub events feed. However, the old project name could be misinterpreted to imply that the Archive was officially connected with the company. This naming confusion is something that has come up a few times and after discussions with the GitHub team, we decided that we should clarify and resolve this. Hence “GHArchive”.

As a side note, big thanks to the many friends at GitHub who volunteered their time over the years to support this project through both code and community initiatives.

### What’s changing, besides the name?

Not much, actually.

- The repository will be renamed to "gharchive.org", but all of the old bookmarks and links should work as expected (GitHub auto-redirects renamed projects).
- The old domain name (githubarchive.org) will similarly redirect to gharchive.org and all old links should auto-redirect to their gharchive.org equivalent.

We're keeping the dataset names on BigQuery same as before to minimize any disruptions. If you do run into any issues with breaking changes as a result of this, let me know!

**Comment by annafil** [comment]
Huge thank you, @igrogik, for working with us to make this happen! 💖

**Comment by igrigorik** [comment]
- [x] update docs and code references to "GH Archive": 31031d6 
- [x] update website to "GH Archive": 9fcbc5e
- [x] rename repo to gharchive.org
- [x] setup DNS, CNAMEs and GitHub config to point to gharchive.org
- [x] move GCP bucket to data.gharchive.org
  - [x] test http://data.gharchive.org/2015-01-01-15.json.gz
- [ ] Redirect http://githubarchive.org/ -> http://gharchive.org/
- [ ] Redirect http://data.githubarchive.org/* -> http://data.gharchive.org/*

Anything else I'm forgetting? :)

**Comment by annafil** [comment]
This looks ⚡️ ! Everything looks good to me. I'm able to wget randomly picked files from data.gharchive.org (My Chrome didn't like the new links but that's probably something on my end)

I think all that's left is to unlock the domain now and we can request a transfer on our side :)

**Comment by igrigorik** [comment]
My bad, thought we had that underway already. Sent you the auth codes to get that moving.

**Comment by annafil** [comment]
Transfer kicked off, and in the meantime `githubarchive.org` is already redirecting to `gharchive.org`. This should gracefully switch over to our redirects when the transfer goes through. 💪 

Thank you so much @igrigorik!!! ✨ 🎉

**Comment by igrigorik** [comment]
Yay! I think we're all set then. Closing this.. please feel free to reopen if you spot anything we missed.
