### ISSUE TITLE
Bandwidth concerns

### ISSUE THREAD

**Issue by utdemir** [igrigorik/gharchive.org#186]
Hey,

Thank you for this great service!

Just wanted to ask you if you have any concerns about excessive bandwidth usage? I am trying to develop a big-data processing framework an as an example I want to point it to `gharchive.org`. However it can cause hundreds of parallel downloads probably many times. Would it disrupt the website or cost you money; or are you okay with it?

**Comment by igrigorik** [comment]
If it's possible to minimize redundant downloads, yes please do so! We're backed by a sturdy CDN, so we can handle the load, but it'll also make your pipelines run faster. Cost wise, it's not a p0 concern, unless we're talking untold tens of terabytes.. :)
