### ISSUE TITLE
[Feature request] add support for GitHub "issue events" in addition to standard "events".

### ISSUE THREAD

**Issue by lukaszgryglicki** [igrigorik/gharchive.org#194]
Hi, is it possible to add support for GitHub issue events (https://developer.github.com/v3/issues/events/) in addition to standard GitHub events (https://developer.github.com/v3/activity/events/, https://developer.github.com/v3/activity/events/types/)? All standard GitHub events have a CamelCase and end with "Event", for example: "PullRequestEvent". GitHub "issue events" are lower case letters with snake_case, for example: "added_to_project", "milestoned" etc. Those events are essential for us because a user can change issue/PR label or milestone without adding a comment. It will not generate a regular GitHub event, so GitHub archives will not contain any information about changed label/milestone. Having GitHub "issue events" supported in GitHub archives would create an event "milestoned" or "labeled". I can help implement this if you give your OK.

**Comment by igrigorik** [comment]
If they're not included in the public /events stream, unfortunately no, we cannot not. That said, yes, it would be nice to have those. 

/cc @annafil

**Comment by lukaszgryglicki** [comment]
They're not returned by /events stream, but why not call another GitHub API to get them, specifically: https://developer.github.com/v3/activity/events/#list-issue-events-for-a-repository, https://developer.github.com/v3/issues/events/

**Comment by igrigorik** [comment]
We cannot enumerate all repos and know when to refetch to update the latest events.

**Comment by lukaszgryglicki** [comment]
This is true, we can think about something like the list of unique repositories from the `/events` call.

**Comment by igrigorik** [comment]
That still doesn't answer the question of when to recrawl, and we cannot recrawl all (millions) of repositories due to API constraints — we're basically up against the limit already. 

Unfortunately this is not something we can solve today, unless GitHub team is willing to include these events in the existing public events stream.

/cc @annafil

**Comment by lcy020625** [comment]
Duplicate of #200
