### ISSUE TITLE
PullRequestReviewEvent is not collected

### ISSUE THREAD

**Issue by rmohr** [igrigorik/gharchive.org#197]
Hi,

Can very well be that the event is simply not reported from where gharchive takes the events, but I noticed that `PullRequestReviewCommentEvents` are collected but not [PullRequestReviewEvent](https://developer.github.com/v3/activity/events/types/#pullrequestreviewevent). As a consequence reviews without extra comments are absolutely invisible in the archive and reviews with comments leave only implicit traces because of the logged comment creation.

Is there a way to improve the situation?

**Comment by igrigorik** [comment]
Paging @annafil for sanity check. Are PullRequestReviewEvent's included in the event stream?

**Comment by annafil** [comment]
Unfortunately, `PullRequestReviewEvent` is not available in the event stream right now. I think this is only available as a webhook.

**Comment by rmohr** [comment]
@igrigorik @annafil thank you for clarifying this.

I for instance wanted to analyze purely via the archives how many reviews happend on PRs, if they got approved, changes were requested, and so forth. Without seeing hints about reviews in the archives, I think it is necessary to query all PRs and related review. So I think it would be nice to have it.

Does it make sense to let the issue open to track the desire to have it, or is this something which will not be changed?

**Comment by igrigorik** [comment]
Unfortunately this is not something we can fix on our end. This would be a request to the GitHub team to add that data to the API.. /me looks at @annafil :-)

**Comment by annafil** [comment]
I'll be sure to pass this along :)

**Comment by kristof0425** [comment]
Any news on this topic, @annafil? 🙂I actually work on an another project of mine, where I would need this kind of event to be sent by the Github API.
