### ISSUE TITLE
Invalid response headers

### ISSUE THREAD

**Issue by Ulfasaar** [igrigorik/gharchive.org#202]
First off I wanted to say thank you for working on this project and making it possible to gather historical Github data easily.

I just wanted to let you guys know that the response headers for the URLs you have on your website seem to be incorrect. 

My best guess is that the files are gzipped either in your data store or before they are sent to a user, however the gzip headers don't appear to be set which results in weird issues with browsers such as Firefox processing the request incorrectly, and with business firewalls blocking said responses due to not being able to decompress the response to scan it for viruses.

**Comment by igrigorik** [comment]
I believe it should be fixed now. Running a batch job to update content-type to 'application/gzip', and it should be setting same type for all new uploads moving forward.

If it's still an issue, please reopen.. and thanks for reporting this!
