### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by olearycrew** [igrigorik/gharchive.org#203]
Ever thought about adding GitLab support to the project?  Maybe forking the project/creating gitlabarchive.org?

**Comment by igrigorik** [comment]
Interesting idea. I'm not familiar with GitLab.. do they provide equivalent / similar APIs for tracking public activity?

**Comment by voxpelli** [comment]
Ping @brendano86, in case you missed the response from @igrigorik 🙂 

Having public pubsub channels for both GitLab and GitHub would be very nice for data analysis purposes like this repo.

**Comment by hamelsmu** [comment]
cc: @annafil anything we can do to support this?

**Comment by 983** [comment]
@olearycrew The GitLab API currently does not allow bulk data collection.

> 1.3. When using, or attempting to use, the GitLab APIs, you agree:
> [...]
>  1.3.9. Not to use the GitLab APIs for the bulk collection or scraping of information.

And if you were to remove that clause, I have a feeling that there might be a bug report or two about the pagination API.

**Comment by 983** [comment]
Since this issue was closed as "completed" instead of closed as "not planned", I was curious whether GitLab support had been implemented. I downloaded a random dump and checked whether it contained `gitlab` URL, but it did not, so either the traffic is very low, or it has not been implemented.

```bash
wget https://data.gharchive.org/2024-01-01-15.json.gz
gunzip 2024-01-01-15.json.gz
grep -P 'url.{1,20}gitlab' 2024-01-01-15.json
```

**Comment by igrigorik** [comment]
Apologies, no marked incorrectly: this is a wontfix.

**Comment by 983** [comment]
Understandable. Thank you for the clarification.
