### ISSUE TITLE
BigQuery Tables Are Empty

### ISSUE THREAD

**Issue by hamelsmu** [igrigorik/gharchive.org#207]
@igrigorik I am trying to query the BigQuery tables and they are all currently empty.  Do you know what may be wrong?

![image](https://user-images.githubusercontent.com/1483922/52583980-c5c08500-2de5-11e9-96d8-c82e8ec65cdb.png)

and

![image](https://user-images.githubusercontent.com/1483922/52584124-2059e100-2de6-11e9-904d-38fbd1a5b77e.png)

cc: @hohsiangwu

**Comment by igrigorik** [comment]
Hmm, we do not maintain those tables. 

Paging @fhoffa.. he should be able to track down who+why they're empty.

**Comment by hamelsmu** [comment]
@fhoffa would love to hear your thoughts.  We were planning to open source something using this data that I think will be big for the community, will be nice to know if this project is permanently deprecated or if this is a blip.  Thank you!

**Comment by hamelsmu** [comment]
cc: @jlewi if you know anyone or (maybe you know Felipe) as well could use your help finding out what is happening :)
