### ISSUE TITLE
Issue data availability?

### ISSUE THREAD

**Issue by jpreese** [igrigorik/gharchive.org#209]
I'm seeing some discussions from many many years ago that looks like GHArchive logged issue data within GitHub (author, message/content, etc). Though looking through BigQuery on Google, I'm only seeing a "commits" table.

Is there anywhere where Issue data is available? I'm trying to do some sentiment analysis on the responses from community members for repositories.

edit: Here is an example, referring to a githubarchive table https://medium.com/google-cloud/analyzing-github-issues-and-comments-with-bigquery-c41410d3308

**Comment by igrigorik** [comment]
I think you're looking at the wrong project / GitHub dataset. See the example here, which specifically references IssuesEvent's: https://www.gharchive.org/#bigquery

**Comment by jpreese** [comment]
From what I can tell IssueEvent should just be a column in the githubarchive table which doesn't exist in BigQuery (that I can find).

I'm trying to actually find the githubarchive table. Even in the linked article, the "public dataset" link (https://bigquery.cloud.google.com/table/githubarchive:day.20150101) doesn't work anymore.

**Comment by igrigorik** [comment]
Ah, I think I see the confusion here.. The "public dataset" is a frozen in time sample, we maintain our own public project with all the latest data. 

Switch to project > display project > "githubarchive"

That should unlock the dataset, and you should be able to view:
 - https://bigquery.cloud.google.com/table/githubarchive:day.20190221
 - https://bigquery.cloud.google.com/dataset/githubarchive:month
 - https://bigquery.cloud.google.com/dataset/githubarchive:year

**Comment by jpreese** [comment]
Ok yes, that was definitely the problem. The updated UI either didnt have that functionality or it's just way more intuitive in the classic UI. I switched to the classic UI, followed your steps and I can see the table now.

Last question I have for this would be IssuesEvent seems to only be for opening, closing, and reopening issues, and so there seems to be only one comment per issue (the comment when it was opened). 

Does this data set contain -all- comments for an issue somewhere? If I wanted to pull back the entire comment thread for a given issue?

**Comment by jpreese** [comment]
Alright, found the two types I'm interested in. Took a little recon, since I'm not seeing an events table but these are the two required needed for anyone else looking for this information:

WHERE type='IssuesEvent' -- used when an issue is created, closed, reopened. contains initial comment
WHERE type='IssueCommentEvent' -- used when a comment is added to an issue

**Comment by igrigorik** [comment]
Awesome, glad you were able to find it :)
