### ISSUE TITLE
not include StarEvent?

### ISSUE THREAD

**Issue by zicjin** [igrigorik/gharchive.org#218]
api documentation: https://developer.github.com/v3/activity/events/types/#starevent
but I can't find any StarEvent in the json file

**Comment by igrigorik** [comment]
How are you checking for StarEvent? Note that example json "action" is "created", with extra starred_at field.

**Comment by zicjin** [comment]
I can't find any "starred_at" or "StarEvent" strings in 2019-06-10-2.json (a random choice)

**Comment by igrigorik** [comment]
Looks like GitHub does not surface these in their events API then. This is not the only event either.. :(

**Comment by alexey-milovidov** [comment]
It is named WatchEvent, not StarEvent.
