### ISSUE TITLE
Missing actor.id before 2015

### ISSUE THREAD

**Issue by LLucchini** [igrigorik/gharchive.org#219]
Downloading gharchive from bigquery I found that some actor.id are missing before 2015 but I didn't understand why. Can you help me out?

Thank you in advance for your time!

Lorenzo

**Comment by igrigorik** [comment]
GitHub API format changed over the years, so there is no guarantee that it's consistent across all the archives, unfortunately: new fields were added, some were removed, etc.

**Comment by LLucchini** [comment]
Thanks a lot.
