### ISSUE TITLE
Lots of missing data over the last day

### ISSUE THREAD

**Issue by mikeal** [igrigorik/gharchive.org#222]
Looks like `2019-09-12-8.json.gz` through `2019-09-13-5.json.gz` is missing.

If permanent, that’s one of the biggest holes in the data set so far 😢

**Comment by igrigorik** [comment]
😢 indeed.. This was an issue on the crawler. 

I resolved the problem last night, but unfortunately the data during this period is missing / can't bring it back — le sigh. Sorry folks!
