### ISSUE TITLE
Provide an archive index

### ISSUE THREAD

**Issue by edigaryev** [igrigorik/gharchive.org#230]
Currently http://data.gharchive.org/ only lists first 2,000 hours of GH Archive data.

It would be nice if the full index would be provided, similarly to [Common Crawl](https://commoncrawl.org/the-data/get-started/), so that one can estimate the data size before downloading and processing it.

**Comment by isra17** [comment]
This is s3, you can use the usual parameters: https://docs.aws.amazon.com/AmazonS3/latest/API/archive-RESTBucketGET.html

**Comment by edigaryev** [comment]
@isra17 it still won't return more than 1,000 keys at once (e.g. http://data.gharchive.org/?max-keys=9000), but the manual suggests the use of `NextContinuationToken`, so I guess this can be considered as resolved.

Thanks!
