### ISSUE TITLE
Will this project continue to work for several years in the future?

### ISSUE THREAD

**Issue by Alanscut** [igrigorik/gharchive.org#236]
Hi Ilya @igrigorik ,

Thank you very much for the convenience of the archive project, it is really a great tool and helped me a lot. May I ask, will this project continue to work for several years in the future?

Cheers,
Alan

**Comment by igrigorik** [comment]
Hi Alan. Glad its been useful! No plan to stop, unless GitHub decides to drop the API. :-)
