### ISSUE TITLE
BigQuery Access Denied Error

### ISSUE THREAD

**Issue by emalgorithm** [igrigorik/gharchive.org#237]
When following the instructions in https://www.gharchive.org/#bigquery and run the example query, I get the error: 
"Access Denied: Project githubarchive: User does not have bigquery.jobs.create permission in project githubarchive."

Any suggestions? Thanks

**Comment by igrigorik** [comment]
You cannot execute queries on behalf of the project, you need to create own project in GCP console and then run queries against the public dataset through that.

**Comment by emalgorithm** [comment]
It works, thanks!

**Comment by rodrigolece** [comment]
Ok found it! It turns out that I can run the snippets of code as they are if I select my own project on the top left of BigQuery. So confusing...
