### ISSUE TITLE
Conversion to graphql ID

### ISSUE THREAD

**Issue by xloem** [igrigorik/gharchive.org#240]
Hi,

I've been working with the json event archive files, and I was wondering how to get the base64 ID used in the github graphql api, from the integer ID used in the files.  Is this something that is doable?

**Comment by xloem** [comment]
(by inspection, it looks like it's a number and keyword unique to the datatype, prefixing the base 10 id, all base64 encoded.  seems pretty convertible.)

**Comment by igrigorik** [comment]
Good question, not sure.. we'd need to ask the folks at GitHub!
