### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by sunilale0** [igrigorik/gharchive.org#242]
``` python
import urllib.request

link2 = "https://data.gharchive.org/2020-10-01-09.json.gz"
with urllib.request.urlopen(link2) as response:
   html = response.read()
```

I keep getting this error. I tried it with different dates and in different python notebooks, but I still have the same issue.

```
HTTPError                                 Traceback (most recent call last)
<ipython-input-2-3c7c36ab2244> in <module>()
      2 
      3 link2 = "https://data.gharchive.org/2020-10-01-09.json.gz"
----> 4 with urllib.request.urlopen(link2) as response:
      5    html = response.read()

5 frames
/usr/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: Forbidden
```

**Comment by andreygursky** [comment]
> https://data.gharchive.org/2020-10-01-09.json.gz

gives me "ERROR 404: Not Found". The URL should be https://data.gharchive.org/2020-10-01-9.json.gz (the last number is the day hour (0, 1,.. 23) with no need of the leading zero).

**Comment by sunilale0** [comment]
Thank you. If I copy and paste the link https://data.gharchive.org/2020-10-01-9.json.gz, a data file is download. So, I see that that is the correct link. The above code with that correction in the link still gives me the same message: Forbidden.

**Comment by andreygursky** [comment]
Python 3.6 urllib sets default User-Agent to "Python-urllib/3.6". For some reason the User-Agent 'Python-urllib' (regardless of particular Python version) is forbidden, though even an empty User-Agent is allowed.

**Comment by sunilale0** [comment]
@andreygursky, thank you very much for the help. Adding an empty User-Agent accordingly helped. My code now looks like the following:
```python
import urllib.request

link2 = "https://data.gharchive.org/2020-10-01-9.json.gz"
req = urllib.request.Request(
  link2,
  headers={
    'User-Agent':''
  }
)

with urllib.request.urlopen(req) as response:
   html = response.read()

```
