### ISSUE TITLE
Add a link to GitHub Explorer

### ISSUE THREAD

**Issue by alexey-milovidov** [igrigorik/gharchive.org#243]
https://gh.clickhouse.tech/explorer/

This is research project that contains interactive access to the database as well as structured compressed dataset (the dataset is just 73 GB).

**Comment by igrigorik** [comment]
Oh wow, love the project! Would you be willing to put together a quick PR to add it to the list?

**Comment by alexey-milovidov** [comment]
Ok, I will submit a PR.

**Comment by alexey-milovidov** [comment]
Here we go: https://github.com/igrigorik/gharchive.org/pull/244
