### ISSUE TITLE
missing year.2020 table

### ISSUE THREAD

**Issue by willnorris** [igrigorik/gharchive.org#246]
It doesn't look like the yearly table for 2020 got created. That doesn't seem to be done in https://github.com/igrigorik/gharchive.org/blob/master/crawler/tasks.cron, so I assume it's a manual process?

**Comment by lucianoviola** [comment]
Stumbled upon this same issue.

**Comment by igrigorik** [comment]
Doh. Automation fail, again. Thanks for the nudge guys! 

![image](https://user-images.githubusercontent.com/10652/109759026-460adc00-7ba1-11eb-9016-b50bd4bb662b.png)

Should be live now.
