### ISSUE TITLE
Can we see private repos within this dataset?

### ISSUE THREAD

**Issue by vanessailana** [igrigorik/gharchive.org#251]
Within the dataset are we able to view user contributions for private repositories. For instance, I am getting a lot of activity for the  LombiqBot on Github. For instance,  for 8-25-2020  I get 2938678 PullRequest Events. And LombiqBot is a trending user on https://www.gitlive.net/.    But, if I head to https://github.com/LombiqBot,  there are no contributions visible for 2020.

**Comment by vanessailana** [comment]
Received my answer. Thanks!

**Comment by jiagengliu** [comment]
> Received my answer. Thanks!

Hi Vanessa, I wonder if you can share your answer? I am also confused by the activity.

**Comment by igrigorik** [comment]
No, you cannot see private repos. Unless, a private repo was made public and history is pushed.
