### ISSUE TITLE
updated table-ranges.sql for BigQuery snippets on gharchive.org

### ISSUE THREAD

**Issue by amcasari** [igrigorik/gharchive.org#254]
Commented on [the gist directly](https://gist.github.com/igrigorik/1cf65f6528e27ed1a580), but not sure if that shows up in the project at all.

BigQuery has [updated Legacy + Standard SQL formatting for table wildcards](https://cloud.google.com/bigquery/docs/querying-wildcard-tables#querying_all_tables_in_a_dataset) so these snippets no longer work on githubarchive on BQ. 

I was able to get the same desired results using _TABLE_SUFFIX, if it helps update documentation: https://gist.github.com/amcasari/6a9d971aadf33ec0d80ba5cea6c2f98e98e

**Comment by igrigorik** [comment]
Thanks for flagging this! Updated the gist.
