### ISSUE TITLE
githubarchive project missing on Google BigQuery

### ISSUE THREAD

**Issue by jaketg97** [igrigorik/gharchive.org#256]
Hi there! It appears as though the githubarchive project on Google BigQuery is missing. It's no longer accessible through R using BigQuery, and on the online console itself, the project no longer displays any accessible datasets. I have confirmed this across multiple users (i.e. it's not account specific).  On BQ error message = "Not found: Project githubarchive"

Thanks,
Jake

**Comment by nelsonjchen** [comment]
https://twitter.com/igrigorik/status/1431375395849342976

Looks like the archive was restored! Abeit with a bit of data loss but that's OK. 🎉

**Comment by grantmcdermott** [comment]
Great news. @jaketg97 I think you should close then.
