### ISSUE TITLE
No data after 2021-10-22-4.json.gz

### ISSUE THREAD

**Issue by danican98** [igrigorik/gharchive.org#260]
Hello,

Is the service gharchive.org suspended? Last archive 2021-10-22-4.json.gz, after it I get the messages "The specified key does not exist".

Thanks

**Comment by igrigorik** [comment]
We had a few days of downtime, unfortunately. Should be back up and running now.

**Comment by Jeffwan** [comment]
@igrigorik Does it mean the lost data won't be backfilled?

**Comment by igrigorik** [comment]
@Jeffwan yes, unfortunately, we don't have data for that window of time.
