### ISSUE TITLE
Unable to run dataset query in BigQuery

### ISSUE THREAD

**Issue by vlad-isayko** [igrigorik/gharchive.org#280]
Hi @igrigorik 👋

I just try to run this sample:

```sql
SELECT event as issue_status, COUNT(*) as cnt FROM (
  SELECT type, repo.name, actor.login,
    JSON_EXTRACT(payload, '$.action') as event, 
  FROM `githubarchive.day.20190101`
  WHERE type = 'IssuesEvent'
)
GROUP by issue_status;
```
But I got an error in response:`Access Denied: Project githubarchive: User does not have bigquery.jobs.create permission in project githubarchive`

Could you help with this?

**Comment by alexey-milovidov** [comment]
You can check the same query in ClickHouse Playground:
https://play.clickhouse.com/play?user=play#U0VMRUNUIGV2ZW50IGFzIGlzc3VlX3N0YXR1cywgQ09VTlQoKikgYXMgY250IEZST00gCigKICBTRUxFQ1QgZXZlbnRfdHlwZSwgcmVwb19uYW1lLCBhY3Rvcl9sb2dpbiwgYWN0aW9uIGFzIGV2ZW50CiAgRlJPTSBnaXRodWJfZXZlbnRzIFdIRVJFIGNyZWF0ZWRfYXQ6OkRhdGUgPSAnMjAxOS0wMS0wMScgQU5EIGV2ZW50X3R5cGUgPSAnSXNzdWVzRXZlbnQnCikKR1JPVVAgYnkgaXNzdWVfc3RhdHVzOw==

It does not require access and works without authentication.
And the query takes only 36 milliseconds to run.

More info here: https://ghe.clickhouse.tech/

**Comment by igrigorik** [comment]
@vlad-isayko you need to create own / separate project, instructions: https://www.gharchive.org/#bigquery

You're trying to run the query within project that's hosting the dataset.
