### ISSUE TITLE
Events before PublicEvent? 

### ISSUE THREAD

**Issue by jiagengliu** [igrigorik/gharchive.org#298]
I have noticed that GHArchive lacks events that happened before the `PublicEvent`. For example, the first PR of PyTorch according to GHArchive is https://github.com/pytorch/pytorch/pull/480 , so the first 479 pulls and issues are never recorded despite being public now. 

My question is how it's possible to collect this information? They seem important.

**Comment by jiagengliu** [comment]
cc @lukaszgryglicki

**Comment by lukaszgryglicki** [comment]
This one is expected IMHO - GHarchive only has public activity at any given point in time. So, before the `PublicEvent` project was private so its events were not archived then, and now there is no way to get them back.

@igrigorik correct me if I'm wrong...
